name: Deploy Vue App to VPS via SSH and Git Pull

on:
  push:
    branches:
      - main # ou la branche que tu veux déployer

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to VPS and pull latest changes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/front-vue
            git pull origin main
            pnpm install
            pnpm build
